## choices for models


ACCESS_CHOICES = (
    #('private', 'Private (only viewable by those with permission to this doc)'),
    ('public', 'Public'),
    ('organization', 'Your newsroom')
)

NEWSROOM_CHOICES = (
    ('beaufortgazette.com', 'Beaufort Gazette'),
    ('bellinghamherald.com', 'Bellingham Herald'),
    ('bnd.com', 'Bellville News-Democrat'),
    ('bradenton.com', 'Bradenton Herald'),
    ('centredaily.com', 'Centre Daily Times'),
    ('charlotteobserver.com', 'Charlotte Observer'),
    ('elnuevoherald.com', 'El Nuevo Herald'),
    ('fresnobee.com', 'Fresno Bee'),
    ('idahostatesman.com', 'Idaho Statesman'),
    ('islandpacket.com', 'Hilton Head Island Packet'),
    ('kansas.com', 'Wichita Eagle'),
    ('kansascity.com', 'Kansas City Star'),
    ('kentucky.com', 'Lexington Herald-Leader'),
    ('ledger-enquirer.com', 'Columbus Ledger Enquirer'),
    ('macon.com', 'Macon Telegraph'),
    ('mercedsun-star.com', 'Merced Sun-Star'),
    ('miamiherald.com', 'Miami Herald'),
    ('modbee.com', 'Modesto Bee'),
    ('myrtlebeachonline.com', 'Myrtle Beach Sun News'),
    ('heraldonline.com', 'Rock Hill Herald'),
    ('newsobserver.com', 'Raleigh News & Observer'),
    ('sacbee.com', 'Sacramento Bee'),
    ('sanluisobispo.com', 'San Luis Obispo Tribune'),
    ('star-telegram.com', 'Fort Worth Star-Telegram'),
    ('sunherald.com', 'Biloxi Sun Herald'),
    ('thenewstribune.com', 'Tacoma News Tribune'),
    ('theolympian.com', 'The Olympian'),
    ('thestate.com', 'The State'),
    ('tri-cityherald.com', 'Tri-City Herald'),
    ('chapelhillnews.com', 'Chapel Hill News'),
    ('charlotte.com', 'Charlotte Observer'),
    ('easternwakenews.com', 'Eastern Wake News'),
    ('thedurhamnews.com', 'Durham News'),
    ('theherald-nc.com', 'Smithfield Herald'),
    ('carynews.com', 'Cary News'),
    ('mcclatchydc.com', 'McClatchy DC'),
    ('mcclatchy.com', 'McClatchy'),
    ('heraldsun.com', 'Durham Herald Sun')
)

# NEWSROOM_DOMAIN_MAPPING = {
#     'beaufortgazette.com': 'Beaufort Gazette',
#     'bellinghamherald.com': 'Bellingham Herald',
#     'bnd.com': 'Bellville News-Democrat',
#     'bradenton.com': 'Bradenton Herald',
#     'centredaily.com': 'Centre Daily Times',
#     'charlotteobserver.com': 'Charlotte Observer',
#     'elnuevoherald.com': 'El Nuevo Herald',
#     'fresnobee.com': 'Fresno Bee',
#     'idahostatesman.com': 'Idaho Statesman',
#     'islandpacket.com': 'Hilton Head Island Packet',
#     'kansas.com': 'Wichita Eagle',
#     'kansascity.com': 'Kansas City Star',
#     'kentucky.com': 'Lexington Herald-Leader',
#     'ledger-enquirer.com': 'Columbus Ledger Enquirer',
#     'macon.com': 'Macon Telegraph',
#     'mercedsun-star.com': 'Merced Sun-Star',
#     'miamiherald.com': 'Miami Herald',
#     'modbee.com': 'Modesto Bee',
#     'myrtlebeachonline.com': 'Myrtle Beach Sun News',
#     'heraldonline.com': 'Rock Hill Herald',
#     'newsobserver.com': 'Raleigh News & Observer',
#     'sacbee.com': 'Sacramento Bee',
#     'sanluisobispo.com': 'San Luis Obispo Tribune',
#     'star-telegram.com': 'Fort Worth Star-Telegram',
#     'sunherald.com': 'Biloxi Sun Herald',
#     'thenewstribune.com': 'Tacoma News Tribune',
#     'theolympian.com': 'The Olympian',
#     'thestate.com': 'The State',
#     'tri-cityherald.com': 'Tri-City Herald',
#     'chapelhillnews.com': 'Chapel Hill News',
#     'charlotte.com': 'Charlotte Observer',
#     'easternwakenews.com': 'Eastern Wake News',
#     'thedurhamnews.com': 'Durham News',
#     'theherald-nc.com': 'Smithfield Herald',
#     'carynews.com': 'Cary News',
#     'mcclatchydc.com': 'McClatchy DC',
#     'mcclatchy.com': 'McClatchy',
#     'heraldsun.com': 'Durham Herald Sun'
# }
